# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e5053bf8560e608e0e8c7f96e42eea681ca97bc4309251b138b1be28a45fe6790148ff5362b40dcb29de09ea47733b6eafe263999c3f2d10899c30cedc0ab8b

test:
  secret_key_base: 0c064063c72c8aebfaec5bc2039f4b92127216af9b8e6df1abb35d326b34aecae9e5f30567707b4195b7f926a5a595c53ecac0866fa45fcf8378fabe9144f453

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
