source 'https://rubygems.org'


gem 'rails', '4.2.6'
gem 'rails-api'
gem 'spring', :group => :development
gem 'pg'

group :development, :test do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'bullet'
  gem 'meta_request'
  gem 'pry-awesome_print'
  gem 'pry-rails'
  gem 'quiet_assets'
  gem 'rspec-rails'
  gem 'rubocop', require: false
end

gem "devise_token_auth", github: "lynndylanhurley/devise_token_auth"
gem "devise", "~>4.1.1"
gem 'puma'
gem 'rack-cors'
